/* DO NOT EDIT THIS FILE
 * - vm.h (Trilby VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2023
 *
 *   Provides Debug Control Setting for the TRILBY VM
 */
#ifndef VM_H
#define VM_H

// Shared Globals
extern int g_debug_mode; 

#endif
