/* DO NOT EDIT THIS FILE
 * - vm_cs.h (Trilby VM)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2023
 *
 *   Header for the Context Switch system of TRILBY VM
 */
#ifndef VM_CS_H
#define VM_CS_H

#include <pthread.h>
#include "vm_process.h"
#include "hake_sched.h"

// Shared Globals (Condition Variables for Mutex)
extern pthread_cond_t cs_cv;
extern pthread_condattr_t cs_cvattr;
extern pthread_mutex_t cs_cv_m;

// Prototypes
void initialize_cs_system();
void cs_cleanup();
void *cs_thread(void *args);
void cs_hake_process(Process_data_s *proc);
void cs_hake_terminated(pid_t pid, int exit_code);
void cs_suspend(pid_t pid);
void cs_resume(pid_t pid);
void cs_exiting_process(int exit_code);
void print_schedule();
void print_hake_queue(Hake_queue_s *queue);
void print_process_node(Hake_process_s *node);
void start_cs();
void stop_cs();
void print_start_cs();
void print_empty_cs();
void print_stop_cs();
void handle_ctrlc();
void toggle_cs();
void print_cs_status();
void set_run_usec(useconds_t time);
useconds_t get_run_usec();
void set_between_usec(useconds_t time);
useconds_t get_between_usec();
Hake_process_s *get_on_cpu();
Hake_schedule_s *get_schedule();

#endif
